version: "3.8"
services:
  db:
    image: mysql/mysql-server:8.0.19
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=flask_db
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
#    image: 'flask-app:1.0'
    command: bash -c "sh ./entrypoint.sh"
    ports:
      - "5000:5000"
    volumes:
      - .:/flask
    depends_on:
      - db

volumes:
  db_data: