version: "3.8"
services:
  db:
    container_name: db_flask
    image: mysql/mysql-server:8.0.19
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=flask_db
    volumes:
      - db_data:/var/lib/mysql

  app:
    restart: always
    build: .
    container_name: web_flask
    command: bash -c "sh ./bin/entrypoint.sh"
    ports:
      - "5000:5000"
    volumes:
      - .:/flask
    depends_on:
      - db

#  rabbitmq:
#    image: rabbitmq:latest
#    environment:
#      RABBIT_ENV_RABBITMQ_USER: guest
#      RABBIT_ENV_RABBITMQ_PASSWORD: guest

  worker:
    build: .
    container_name: worker
    command: bash -c "sh ./bin/run_worker.sh"
    volumes:
    - .:/flask_lost_and_found
    environment:
      RABBIT_ENV_RABBITMQ_USER: guest
      RABBIT_ENV_RABBITMQ_PASSWORD: guest
    depends_on:
      - redis_server
#      - rabbitmq
      - app

  redis_server:
    image: redis:6-alpine
    container_name: redis


volumes:
  db_data: