"""Create tables

Revision ID: 95c89433b5e7
Revises: 
Create Date: 2021-09-07 11:47:14.511761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c89433b5e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('items',
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lost_date', sa.Date(), nullable=True),
    sa.Column('is_found', sa.Boolean(), nullable=True),
    sa.Column('lost_by_user_id', sa.Integer(), nullable=True),
    sa.Column('found_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['found_by_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['lost_by_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('lost_item_id')
    )
    op.create_index(op.f('ix_items_lost_item_id'), 'items', ['lost_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_lost_item_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('user')
    # ### end Alembic commands ###
