"""Create tables

Revision ID: fed250b3fd36
Revises: 
Create Date: 2021-09-15 05:43:43.854350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed250b3fd36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('task_status', sa.String(length=100), nullable=False),
    sa.Column('task_result', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('items',
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lost_date', sa.Date(), nullable=True),
    sa.Column('is_found', sa.Boolean(), nullable=True),
    sa.Column('lost_by_user_id', sa.Integer(), nullable=True),
    sa.Column('found_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['found_by_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['lost_by_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('lost_item_id')
    )
    op.create_index(op.f('ix_items_lost_item_id'), 'items', ['lost_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_lost_item_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('user')
    op.drop_table('tasks')
    # ### end Alembic commands ###
